spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./h2/oocl-agile-fs
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

  profiles:
    action: local

Server:
  port: 8088

logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR